// ⚠️ AUTO-GENERATED FILE - Do not edit manually
// This file is generated by scripts/generate-blocks.cjs
// Add new blocks to src/blocks/ directory and run: npm run generate-blocks

import { GraphNode } from '../types/graph';
import { BlockEvalRuntime } from '../utils/evalGraphShared';
import { evaluateBeamVisual } from './beamvisual/evaluate';
import { evaluateCalc } from './calc/evaluate';
import { evaluateCases } from './cases/evaluate';
import { evaluateChartLookup } from './chartlookup/evaluate';
import { evaluateCheck } from './check/evaluate';
import { evaluateComment } from './comment/evaluate';
import { evaluateCondition } from './condition/evaluate';
import { evaluateDropdown } from './dropdown/evaluate';
import { evaluateFrame } from './frame/evaluate';
import { evaluateGroupCalc } from './groupcalc/evaluate';
import { evaluateImage } from './image/evaluate';
import { evaluateLoopBlock } from './loopblock/evaluate';
import { evaluateMatrix } from './matrix/evaluate';
import { evaluateMinMax } from './minmax/evaluate';
import { evaluateOutput } from './output/evaluate';
import { evaluatePolargrid } from './polargrid/evaluate';
import { evaluateRef } from './ref/evaluate';
import { evaluateSection } from './section/evaluate';
import { evaluateStdCalc } from './stdcalc/evaluate';
import { evaluateSwitchCalc } from './switchcalc/evaluate';
import { evaluateTableCalc } from './tablecalc/evaluate';
import { evaluateTableValue } from './tablevalue/evaluate';
import { evaluateTitle } from './title/evaluate';
import { evaluateVariable } from './variable/evaluate';
import { evaluateWoodClass } from './woodclass/evaluate';

export type BlockEvaluator = (node: GraphNode, runtime: BlockEvalRuntime) => void;

export const BLOCK_EVALUATORS: Record<string, BlockEvaluator> = {
  beamvisual: evaluateBeamVisual,
  calc: evaluateCalc,
  cases: evaluateCases,
  chartlookup: evaluateChartLookup,
  check: evaluateCheck,
  comment: evaluateComment,
  condition: evaluateCondition,
  dropdown: evaluateDropdown,
  frame: evaluateFrame,
  groupcalc: evaluateGroupCalc,
  image: evaluateImage,
  loopblock: evaluateLoopBlock,
  matrix: evaluateMatrix,
  minmax: evaluateMinMax,
  output: evaluateOutput,
  polargrid: evaluatePolargrid,
  ref: evaluateRef,
  section: evaluateSection,
  stdcalc: evaluateStdCalc,
  switchcalc: evaluateSwitchCalc,
  tablecalc: evaluateTableCalc,
  tablevalue: evaluateTableValue,
  title: evaluateTitle,
  variable: evaluateVariable,
  woodclass: evaluateWoodClass,
};
