// ⚠️ AUTO-GENERATED FILE - Do not edit manually
// This file is generated by scripts/generate-blocks.cjs
// Add new blocks to src/blocks/ directory and run: npm run generate-blocks

import { BlockData, BlockType } from '../types/graph';
import { beamvisualBlock } from './beamvisual';
import { calcBlock } from './calc';
import { casesBlock } from './cases';
import { chartlookupBlock } from './chartlookup';
import { checkBlock } from './check';
import { commentBlock } from './comment';
import { conditionBlock } from './condition';
import { dropdownBlock } from './dropdown';
import { frameBlock } from './frame';
import { groupcalcBlock } from './groupcalc';
import { imageBlock } from './image';
import { loopblockBlock } from './loopblock';
import { matrixBlock } from './matrix';
import { minmaxBlock } from './minmax';
import { outputBlock } from './output';
import { polargridBlock } from './polargrid';
import { refBlock } from './ref';
import { sectionBlock } from './section';
import { stdcalcBlock } from './stdcalc';
import { stiffnesscenterBlock } from './stiffnesscenter';
import { switchcalcBlock } from './switchcalc';
import { tablecalcBlock } from './tablecalc';
import { tablevalueBlock } from './tablevalue';
import { titleBlock } from './title';
import { variableBlock } from './variable';
import { woodclassBlock } from './woodclass';

export const BLOCK_DEFINITIONS = [
  beamvisualBlock,
  calcBlock,
  casesBlock,
  chartlookupBlock,
  checkBlock,
  commentBlock,
  conditionBlock,
  dropdownBlock,
  frameBlock,
  groupcalcBlock,
  imageBlock,
  loopblockBlock,
  matrixBlock,
  minmaxBlock,
  outputBlock,
  polargridBlock,
  refBlock,
  sectionBlock,
  stdcalcBlock,
  stiffnesscenterBlock,
  switchcalcBlock,
  tablecalcBlock,
  tablevalueBlock,
  titleBlock,
  variableBlock,
  woodclassBlock,
] as const;

export const PALETTE = BLOCK_DEFINITIONS.map(({ type, icon, label, color }) => ({ type, icon, label, color }));

export function createDefaultBlockData(type: BlockType): BlockData {
  const definition = BLOCK_DEFINITIONS.find(block => block.type === type);
  if (!definition) throw new Error(`Unbekannter Blocktyp: ${type}`);
  return definition.createDefaultData();
}
