const fs = require('fs');
const path = require('path');

function getBlocksDir() {
  return path.resolve(__dirname, '../src/blocks');
}

function extractExportName(filePath, pattern) {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const match = content.match(pattern);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

function findBlocks() {
  const blocksDir = getBlocksDir();
  const items = fs.readdirSync(blocksDir, { withFileTypes: true });

  return items
    .filter(item => item.isDirectory() && !item.name.startsWith('.') && item.name !== 'types')
    .map(item => {
      const dir = path.join(blocksDir, item.name);
      const defPath = path.join(dir, 'definition.ts');
      const evalPath = path.join(dir, 'evaluate.ts');
      const defaultsPath = path.join(dir, 'defaults.ts');

      const hasDefinition = fs.existsSync(defPath);
      const hasEvaluate = fs.existsSync(evalPath);
      const hasDefaults = fs.existsSync(defaultsPath);

      let blockName = null;
      let evaluatorName = null;
      let themeData = null;
      let blockType = null;
      let defaultFields = null;

      if (hasDefinition) {
        blockName = extractExportName(defPath, /export const (\w+Block):/);
        blockType = extractExportName(defPath, /type:\s*['"]([^'"]+)['"]/);
        // Extract theme data
        const content = fs.readFileSync(defPath, 'utf-8');
        const themeMatch = content.match(/theme:\s*({[\s\S]*?})/);
        if (themeMatch) {
          try {
            const themeStr = themeMatch[1];
            const bgMatch = themeStr.match(/bg:\s*['"]([^'"]+)['"]/);
            const borderMatch = themeStr.match(/border:\s*['"]([^'"]+)['"]/);
            if (bgMatch && borderMatch) {
              themeData = {
                bg: bgMatch[1],
                border: borderMatch[1],
              };
            }
          } catch {}
        }
      }

      if (hasEvaluate) {
        evaluatorName = extractExportName(evalPath, /export function (evaluate\w+)\(/);
      }

      if (hasDefaults && blockType) {
        // Extract default fields from defaults.ts for interface generation
        try {
          const content = fs.readFileSync(defaultsPath, 'utf-8');
          const returnMatch = content.match(/return\s*({[\s\S]*?}\s*);/);
          if (returnMatch) {
            const returnStr = returnMatch[1];
            // Extract field names
            const fields = {};
            const fieldRegex = /(\w+):\s*[^,}]+/g;
            let match;
            while ((match = fieldRegex.exec(returnStr)) !== null) {
              fields[match[1]] = true;
            }
            defaultFields = Object.keys(fields);
          }
        } catch {}
      }

      return {
        name: item.name,
        dir,
        blockName,
        blockType,
        evaluatorName,
        themeData,
        defaultFields,
        hasDefinition,
        hasEvaluate,
        hasDefaults,
      };
    })
    .filter(block => block.hasDefinition && block.hasEvaluate && block.blockName && block.evaluatorName && block.blockType);
}

function generateIndexTs(blocks) {
  const imports = blocks
    .map(b => `import { ${b.blockName} } from './${b.name}';`)
    .join('\n');

  const arrayItems = blocks
    .map(b => `  ${b.blockName},`)
    .join('\n');

  return `// ⚠️ AUTO-GENERATED FILE - Do not edit manually
// This file is generated by scripts/generate-blocks.cjs
// Add new blocks to src/blocks/ directory and run: npm run generate-blocks

import { BlockData, BlockType } from '../types/graph';
${imports}

export const BLOCK_DEFINITIONS = [
${arrayItems}
] as const;

export const PALETTE = BLOCK_DEFINITIONS.map(({ type, icon, label, color }) => ({ type, icon, label, color }));

export function createDefaultBlockData(type: BlockType): BlockData {
  const definition = BLOCK_DEFINITIONS.find(block => block.type === type);
  if (!definition) throw new Error(\`Unbekannter Blocktyp: \${type}\`);
  return definition.createDefaultData();
}
`;
}

function generateEvaluatorsTs(blocks) {
  const imports = blocks
    .map(b => `import { ${b.evaluatorName} } from './${b.name}/evaluate';`)
    .join('\n');

  const objectItems = blocks
    .map(b => `  ${b.name}: ${b.evaluatorName},`)
    .join('\n');

  return `// ⚠️ AUTO-GENERATED FILE - Do not edit manually
// This file is generated by scripts/generate-blocks.cjs
// Add new blocks to src/blocks/ directory and run: npm run generate-blocks

import { GraphNode } from '../types/graph';
import { BlockEvalRuntime } from '../utils/evalGraphShared';
${imports}

export type BlockEvaluator = (node: GraphNode, runtime: BlockEvalRuntime) => void;

export const BLOCK_EVALUATORS: Record<string, BlockEvaluator> = {
${objectItems}
};
`;
}

function getComponentName(blockDir) {
  try {
    const content = fs.readFileSync(path.join(blockDir, 'BackendNode.tsx'), 'utf-8');
    const match = content.match(/export function (\w+Node)\(/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

function generateBlockNodesTs(blocks) {
  const imports = blocks
    .map(b => {
      const componentName = getComponentName(b.dir);
      if (!componentName) return null;
      return `import { ${componentName} } from '../../../blocks/${b.name}/BackendNode';`;
    })
    .filter(Boolean)
    .join('\n');

  const objectItems = blocks
    .map(b => {
      const componentName = getComponentName(b.dir);
      if (!componentName) return null;
      return `  ${b.name}: ${componentName},`;
    })
    .filter(Boolean)
    .join('\n');

  return `// ⚠️ AUTO-GENERATED FILE - Do not edit manually
// This file is generated by scripts/generate-blocks.cjs
// Add new blocks to src/blocks/ directory and run: npm run generate-blocks

${imports}

export const nodeTypes = {
${objectItems}
};
`;
}

function generateBlockInterfaces(blocks) {
  return blocks
    .map(b => {
      const fields = b.defaultFields || ['name', 'label'];
      const fieldDefs = fields
        .map(f => {
          if (f === 'kind') return `  kind: '${b.blockType}';`;
          if (f === 'description') return `  ${f}?: string;`;
          return `  ${f}: string;`;
        })
        .join('\n');

      return `export interface ${capitalize(b.blockName.replace(/Block$/, ''))}Data {
${fieldDefs}
}`;
    })
    .join('\n\n');
}

function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function updateTypesGraphTs(blocks) {
  const typesPath = path.resolve(__dirname, '../src/types/graph.ts');
  let content = fs.readFileSync(typesPath, 'utf-8');

  // Update BlockType union
  const blockTypeMatch = content.match(/export type BlockType =\s*\|([\s\S]*?);/);
  if (blockTypeMatch) {
    const existingTypes = blockTypeMatch[1]
      .split('|')
      .map(t => t.trim())
      .map(t => t.split('//')[0].trim())
      .filter(Boolean)
      .map(t => t.replace(/^'|'$/g, ''));

    const newBlocks = blocks
      .map(b => b.blockType)
      .filter(type => !existingTypes.includes(type));

    if (newBlocks.length > 0) {
      const newTypeEntries = newBlocks
        .map(name => `  | '${name}'`)
        .join('\n');

      const oldType = blockTypeMatch[0];
      const newType = oldType.replace(/;$/, `\n${newTypeEntries}\n;`);
      content = content.replace(oldType, newType);
    }
  }

  // Find where to insert new interfaces (before OutputData or at end of interfaces)
  const outputDataMatch = content.match(/export interface OutputData[\s\S]*?\n}/);
  if (outputDataMatch) {
    const insertPos = content.lastIndexOf(outputDataMatch[0]);
    const newInterfaces = generateBlockInterfaces(
      blocks.filter(b => !content.includes(`interface ${capitalize(b.blockName.replace(/Block$/, ''))}Data`))
    );

    if (newInterfaces) {
      content = content.slice(0, insertPos) + newInterfaces + '\n\n' + content.slice(insertPos);
    }
  }

  // Update BlockData union
  const blockDataMatch = content.match(/export type BlockData =\s*([\s\S]*?);/);
  if (blockDataMatch) {
    const existingData = blockDataMatch[1]
      .split('|')
      .map(t => t.trim())
      .filter(Boolean);

    const newDataInterfaces = blocks
      .map(b => `${capitalize(b.blockName.replace(/Block$/, ''))}Data`)
      .filter(d => !blockDataMatch[1].includes(d));

    if (newDataInterfaces.length > 0) {
      const oldDataUnion = blockDataMatch[0];
      const newEntry = newDataInterfaces.join(' | ');
      const newDataUnion = oldDataUnion.replace(/;$/, ` | ${newEntry};`);
      content = content.replace(oldDataUnion, newDataUnion);
    }
  }

  fs.writeFileSync(typesPath, content, 'utf-8');
}

function updateBlockSharedTheme(blocks) {
  const sharedPath = path.resolve(__dirname, '../src/components/admin/graph/BlockNodeShared.tsx');
  let content = fs.readFileSync(sharedPath, 'utf-8');

  const themeStart = content.indexOf('export const THEME');
  const themeEnd = content.indexOf('};', themeStart) + 2;

  if (themeStart === -1) {
    console.warn('⚠️ Could not find THEME in BlockNodeShared.tsx');
    return;
  }

  // Build new THEME
  const themeItems = blocks
    .map(b => {
      const icon = extractExportName(path.join(b.dir, 'definition.ts'), /icon:\s*['"]([^'"]+)['"]/);
      const label = extractExportName(path.join(b.dir, 'definition.ts'), /label:\s*['"]([^'"]+)['"]/);
      if (b.themeData) {
        return `  ${b.name}: { bg: '${b.themeData.bg}', border: '${b.themeData.border}', icon: '${icon || '🟪'}', label: '${label || 'Block'}' },`;
      }
      return null;
    })
    .filter(Boolean)
    .join('\n');

  const newTheme = `export const THEME: Record<string, { bg: string; border: string; icon: string; label: string }> = {
${themeItems}
};`;

  const oldTheme = content.substring(themeStart, themeEnd);
  content = content.replace(oldTheme, newTheme);

  fs.writeFileSync(sharedPath, content, 'utf-8');
}

// Main
console.log('🔧 Generating block system files...\n');

const blocks = findBlocks();
const blocksDir = getBlocksDir();

const indexPath = path.join(blocksDir, 'index.ts');
const evaluatorsPath = path.join(blocksDir, 'evaluators.ts');
const blockNodesPath = path.resolve(__dirname, '../src/components/admin/graph/BlockNodes.tsx');

const indexContent = generateIndexTs(blocks);
const evaluatorsContent = generateEvaluatorsTs(blocks);
const blockNodesContent = generateBlockNodesTs(blocks);

fs.writeFileSync(indexPath, indexContent, 'utf-8');
fs.writeFileSync(evaluatorsPath, evaluatorsContent, 'utf-8');
fs.writeFileSync(blockNodesPath, blockNodesContent, 'utf-8');

// Update types/graph.ts
updateTypesGraphTs(blocks);

// Update BlockNodeShared.tsx THEME
updateBlockSharedTheme(blocks);

console.log(`✅ Generated ${blocks.length} blocks`);
console.log('   - ' + indexPath.replace(__dirname + '/../', ''));
console.log('   - ' + evaluatorsPath.replace(__dirname + '/../', ''));
console.log('   - ' + blockNodesPath.replace(__dirname + '/../', ''));
console.log('   - BlockNodeShared.tsx (THEME updated)');
console.log('   - types/graph.ts (BlockType + BlockData updated)');
console.log('\n🎉 Done!');
