const fs = require('fs');
const path = require('path');

function getBlocksDir() {
  return path.resolve(__dirname, '../src/blocks');
}

function extractExportName(filePath, pattern) {
  try {
    const content = fs.readFileSync(filePath, 'utf-8');
    const match = content.match(pattern);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

function findBlocks() {
  const blocksDir = getBlocksDir();
  const items = fs.readdirSync(blocksDir, { withFileTypes: true });

  return items
    .filter(item => item.isDirectory() && !item.name.startsWith('.') && item.name !== 'types')
    .map(item => {
      const dir = path.join(blocksDir, item.name);
      const defPath = path.join(dir, 'definition.ts');
      const evalPath = path.join(dir, 'evaluate.ts');

      const hasDefinition = fs.existsSync(defPath);
      const hasEvaluate = fs.existsSync(evalPath);

      let blockName = null;
      let evaluatorName = null;

      if (hasDefinition) {
        blockName = extractExportName(defPath, /export const (\w+Block):/);
      }

      if (hasEvaluate) {
        evaluatorName = extractExportName(evalPath, /export function (evaluate\w+)\(/);
      }

      return {
        name: item.name,
        dir,
        blockName,
        evaluatorName,
        hasDefinition,
        hasEvaluate,
      };
    })
    .filter(block => block.hasDefinition && block.hasEvaluate && block.blockName && block.evaluatorName);
}

function generateIndexTs(blocks) {
  const imports = blocks
    .map(b => `import { ${b.blockName} } from './${b.name}';`)
    .join('\n');

  const arrayItems = blocks
    .map(b => `  ${b.blockName},`)
    .join('\n');

  return `// ⚠️ AUTO-GENERATED FILE - Do not edit manually
// This file is generated by scripts/generate-blocks.js
// Add new blocks to src/blocks/ directory and run: npm run generate-blocks

import { BlockData, BlockType } from '../types/graph';
${imports}

export const BLOCK_DEFINITIONS = [
${arrayItems}
] as const;

export const PALETTE = BLOCK_DEFINITIONS.map(({ type, icon, label, color }) => ({ type, icon, label, color }));

export function createDefaultBlockData(type: BlockType): BlockData {
  const definition = BLOCK_DEFINITIONS.find(block => block.type === type);
  if (!definition) throw new Error(\`Unbekannter Blocktyp: \${type}\`);
  return definition.createDefaultData();
}
`;
}

function generateEvaluatorsTs(blocks) {
  const imports = blocks
    .map(b => `import { ${b.evaluatorName} } from './${b.name}/evaluate';`)
    .join('\n');

  const objectItems = blocks
    .map(b => `  ${b.name}: ${b.evaluatorName},`)
    .join('\n');

  return `// ⚠️ AUTO-GENERATED FILE - Do not edit manually
// This file is generated by scripts/generate-blocks.js
// Add new blocks to src/blocks/ directory and run: npm run generate-blocks

import { GraphNode } from '../types/graph';
import { BlockEvalRuntime } from '../utils/evalGraphShared';
${imports}

export type BlockEvaluator = (node: GraphNode, runtime: BlockEvalRuntime) => void;

export const BLOCK_EVALUATORS: Record<string, BlockEvaluator> = {
${objectItems}
};
`;
}

// Main
const blocks = findBlocks();
const blocksDir = getBlocksDir();

const indexPath = path.join(blocksDir, 'index.ts');
const evaluatorsPath = path.join(blocksDir, 'evaluators.ts');

const indexContent = generateIndexTs(blocks);
const evaluatorsContent = generateEvaluatorsTs(blocks);

fs.writeFileSync(indexPath, indexContent, 'utf-8');
fs.writeFileSync(evaluatorsPath, evaluatorsContent, 'utf-8');

console.log(`✅ Auto-generated ${blocks.length} blocks`);
console.log('   - ' + indexPath.replace(__dirname + '/../', ''));
console.log('   - ' + evaluatorsPath.replace(__dirname + '/../', ''));
