// ⚠️ AUTO-GENERATED FILE - Do not edit manually
// This file is generated by scripts/generate-blocks.cjs
// Add new blocks to src/blocks/ directory and run: npm run generate-blocks

import { BeamVisualNode } from '../../../blocks/beamvisual/BackendNode';
import { CalcNode } from '../../../blocks/calc/BackendNode';
import { CasesNode } from '../../../blocks/cases/BackendNode';
import { ChartLookupNode } from '../../../blocks/chartlookup/BackendNode';
import { CheckNode } from '../../../blocks/check/BackendNode';
import { CommentNode } from '../../../blocks/comment/BackendNode';
import { ConditionNode } from '../../../blocks/condition/BackendNode';
import { DropdownNode } from '../../../blocks/dropdown/BackendNode';
import { FrameNode } from '../../../blocks/frame/BackendNode';
import { GroupCalcNode } from '../../../blocks/groupcalc/BackendNode';
import { ImageNode } from '../../../blocks/image/BackendNode';
import { LoopBlockNode } from '../../../blocks/loopblock/BackendNode';
import { MatrixNode } from '../../../blocks/matrix/BackendNode';
import { MinMaxNode } from '../../../blocks/minmax/BackendNode';
import { OutputNode } from '../../../blocks/output/BackendNode';
import { RefNode } from '../../../blocks/ref/BackendNode';
import { SectionNode } from '../../../blocks/section/BackendNode';
import { StdCalcNode } from '../../../blocks/stdcalc/BackendNode';
import { SwitchCalcNode } from '../../../blocks/switchcalc/BackendNode';
import { TableCalcNode } from '../../../blocks/tablecalc/BackendNode';
import { TableValueNode } from '../../../blocks/tablevalue/BackendNode';
import { TitleNode } from '../../../blocks/title/BackendNode';
import { VariableNode } from '../../../blocks/variable/BackendNode';
import { WoodClassNode } from '../../../blocks/woodclass/BackendNode';

export const nodeTypes = {
  beamvisual: BeamVisualNode,
  calc: CalcNode,
  cases: CasesNode,
  chartlookup: ChartLookupNode,
  check: CheckNode,
  comment: CommentNode,
  condition: ConditionNode,
  dropdown: DropdownNode,
  frame: FrameNode,
  groupcalc: GroupCalcNode,
  image: ImageNode,
  loopblock: LoopBlockNode,
  matrix: MatrixNode,
  minmax: MinMaxNode,
  output: OutputNode,
  ref: RefNode,
  section: SectionNode,
  stdcalc: StdCalcNode,
  switchcalc: SwitchCalcNode,
  tablecalc: TableCalcNode,
  tablevalue: TableValueNode,
  title: TitleNode,
  variable: VariableNode,
  woodclass: WoodClassNode,
};
